//login

export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_FAILURE="LOGIN_FAILURE"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_SUCCESS_LOGOUT="LOGIN_SUCCESS_LOGOUT"

//admin
export const LOGIN_ADMIN_REQUEST="LOGIN_ADMIN_REQUEST"
export const LOGIN_ADMIN_FAILURE="LOGIN_ADMIN_FAILURE"
export const LOGIN_ADMIN_SUCCESS="LOGIN_ADMIN_SUCCESS"